### ISSUE TITLE
Wrong and confusing warning message

### ISSUE THREAD

**Issue by FredericLeuba** [time2backup/time2backup#183]
Hello Jean,
First, thanks for your great work and super-useful software.
Now, just a note to report an issue.

# Issue

I've got the following message:

> [WARNING]  Destination filesystem not found. Continue in trash mode.

1. This is wrong, because my remote destination filesystem is properly mounted. So it is very confusing, and led me to canceling the backup, although you told me afterwards that it is ok to continue.
2. Mentioning "Trash mode" is very confusing too... What is it ? Trash sounds like everything is going to be moved to trash... and lost somehow.

Could you please update the message with something more useful and obvious to the user?

Thanks

# Context

1. Time2backup version 1.4.0
2. Backup to a local folder on which is mounted a remote volume, using sshfs
3. OS: MacOS Mojave

**Comment by pruje** [comment]
Hi Frederic, and thanks for your support!
I've removed the message, because you're right, end users does not need this information.
The message is now only available in debug mode.
I've fixed it in commit fcf66331eb60bc6d558abb7eaaa297ecb74b3def and will be published with the next 1.5.0 release (currently in beta)
